### ISSUE TITLE
License Exemption wording

### ISSUE THREAD

**Issue by ghost** [mcs-sdk/mcs#4]
From forums.

concerning LGPL license, due to IL2CPP static linking. We need an exemption text in the license allowing us to use it as intended.

https://forum.unity.com/threads/released-morph-character-system-mcs-male-and-female.355675/page-72#post-4584619

**Comment by lazlo-bonin** [comment]
Hi,

On the Unity forum thread, @jjanzer [said this LGPL restriction was unintentional and that it would be modified](https://forum.unity.com/threads/released-morph-character-system-mcs-male-and-female.355675/page-72#post-4584619). There hasn't been an update on the situation for 6 months. Is the license ever getting changed? If not, we simply legally cannot use MCS in any build targetting consoles or even a standalone IL2CPP build.

**Comment by jjanzer** [comment]
Sorry, we've gotten caught up with a lot of work recently and this has slipped. I'll talk to legal this week and get a decision about this change ASAP.

**Comment by jjanzer** [comment]
This is resolved now with the updated exemption.
